import os, json
from typing import List, Tuple

def write_datapack(voxels: List[Tuple[int,int,int]], out_dir: str, namespace: str = "floorplan",
                   function_name: str = "build", block_id: str = "minecraft:stone") -> str:
    pack_id = f"{namespace}_pack"
    pack_dir = os.path.join(out_dir, pack_id)
    func_dir = os.path.join(pack_dir, "data", namespace, "functions")
    os.makedirs(func_dir, exist_ok=True)

    mcmeta = {"pack": {"pack_format": 48, "description": "Floorplan voxelizer"}}
    with open(os.path.join(pack_dir, "pack.mcmeta"), "w", encoding="utf-8") as f:
        json.dump(mcmeta, f, ensure_ascii=False, indent=2)

    func_path = os.path.join(func_dir, f"{function_name}.mcfunction")
    with open(func_path, "w", encoding="utf-8") as f:
        f.write("# Autogenerated\n")
        for x, y, z in voxels:
            f.write(f"setblock ~{x} ~{y} ~{z} {block_id}\n")
    return pack_dir
